### ISSUE TITLE
Feature Request: allow reverse sorting for XML feed

### ISSUE THREAD

**Issue by moriahchandler** [AndreyVMarkelov/andreymarkelov-atlas-plugins-requestedfields#11]
When we get a dropdown field list using XML, it returns it in alphabetical order.  Since we are using it to list build numbers (example: r568873.dev), we would really like it to be in reverse alpha order so that the newest build is first in the list.

**Comment by AndreyVMarkelov** [comment]
Hi. WIll look at

**Comment by AndreyVMarkelov** [comment]
Done. added sort options
