### ISSUE TITLE
Need an update for JIRA 7.1

### ISSUE THREAD

**Issue by tligda** [AndreyVMarkelov/andreymarkelov-atlas-plugins-requestedfields#13]
Greetings!

This add-on needs an update for JIRA 7.1. It currently shows compatibility up to JIRA 7.0, but not for JIRA 7.1.

I am currently running JIRA 7.1.9 and the add-on is working for the most part, but it seems like it may be causing problems with indexing.

**Comment by lwrbakro** [comment]
Same for 7.4.1
