### ISSUE TITLE
not work well with HTTPS ssl 

### ISSUE THREAD

**Issue by longlone** [AndreyVMarkelov/andreymarkelov-atlas-plugins-requestedfields#4]
I try to get the select list from a https URL but it always fail with
avax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching foo.bar found
I already add the SSL certificates into JIRA but it looks like this plugin does not get the SSL certificates from JIRA. Does anyone help on this part? thanks you so much.

longlone

**Comment by AndreyVMarkelov** [comment]
Done in the last version for jira 7.
