### ISSUE TITLE
404 Error when attempting to "Edit JSON HTTP Settings"

### ISSUE THREAD

**Issue by shylahw** [AndreyVMarkelov/andreymarkelov-atlas-plugins-requestedfields#5]
I am receiving a 404 error when I create a custom field and click the "Edit JSON HTTP Settings" link.

**Comment by ccpoffshoretools** [comment]
i am also getting same error. Kindly help on this .

**Comment by AndreyVMarkelov** [comment]
Fixed in the last version.
