### ISSUE TITLE
HTTP Feed Custom Fields - free text searcher or renderer

### ISSUE THREAD

**Issue by leosjunek** [AndreyVMarkelov/andreymarkelov-atlas-plugins-requestedfields#8]
Plugin HTTP Feed Custom Fields do a great job at populating custom field with values from remote location. However its equipped with only specific searchers e.g. JSON Request Custom Field Searcher. When searching user must type exact string of some custom field value. It's not user-friendly specially in case list of custom field is numerous and it's values are similar, because user must guess exact string. 

Could you implement free text searcher or renderer that allows autocomplete function into your plugin, please?

**Comment by leosjunek** [comment]
Hello Andrey,
has the mentioned feature been done? Does plugin version 1.1.8 work with that?

Regards
Leoš

**Comment by AndreyVMarkelov** [comment]
Done.
